# Generated by Django 5.1.1 on 2024-10-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplaz', '0002_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
