# Generated by Django 5.1.1 on 2024-10-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplaz', '0003_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
