# Generated by Django 5.1.1 on 2024-10-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplaz', '0004_product_size_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
